spring:
  profiles:
    active: dev
  mail:
    username: 473692484@qq.com
    password: cremtxzekzmbbjie
    host: smtp.qq.com
    properties:
      mail:
        #将发送邮件得过程打印在控制台
        #        debug: true
        smtp:
          ssl:
            enable: true

  redis:
    port: 8082
    host: 120.79.64.26
    database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 60000
    password: test123456

mybatis-plus:
  # 日志配置 控制台输出
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

